In [1]:
import numpy as np

Ваша задача проверить, что найденное вами решение линейной регрессии действительно корректно.

$$||Y-X\beta||^2 \to min$$

1) Сгенерируйте случайную матрицу $X$ и вектор $Y$

2) Найдите коэфициенты $\beta$ и $\hat{y}$

3) Покажите, что ваш вектор действительно является проекцией на линейную оболочку столбцов
![title](linreg.jpg)

In [57]:
L = 10
N = 10

In [58]:
X = np.random.normal(size=(L, N))
Y = np.random.normal(size=(L, 1))
print X

[[-2.24131743  1.25421741 -0.51197239  0.54504537  0.60899316  3.0483259
   0.30374409 -0.44081619  3.02707794  0.82796291]
 [ 0.37089764  0.48329454  0.50343028 -0.63660812  0.27999988  0.24369672
  -0.66504154 -0.23747897  0.61372305 -0.64236181]
 [-0.36129342 -0.69361068  1.52007458 -2.15778043  0.83523928  0.33819532
  -1.03572565 -1.62115018 -2.77889292 -0.16864059]
 [ 0.09756022 -0.8617483   0.61407916 -0.43919227  0.28920168  0.68398623
  -1.42598513  2.6685608  -0.16416609 -0.28706465]
 [-1.31037972  0.04537863 -0.85133952 -1.28885585 -0.64728623  0.47198653
   1.16340154 -0.4590467   0.14469881 -1.61815119]
 [-1.50919108 -1.81706477  0.967396   -0.70638907  0.34234815 -0.56791228
  -1.02023263 -0.51519265  0.05423136  0.08310145]
 [ 0.10514336 -0.08377262  0.60281775  0.49140175  0.91524224 -1.66853674
  -1.13543438 -0.19555624  0.58865191 -1.8967206 ]
 [-1.69689463 -0.63040096 -1.59092884 -1.07230769 -0.08827373  0.17255883
  -0.2589676   2.11591444  0.92184836  0.0495917 ]
 

In [59]:
print Y

[[ 0.69377254]
 [-0.30208078]
 [-0.19597147]
 [ 0.62174464]
 [ 0.49624943]
 [-0.43494333]
 [ 1.04819821]
 [-0.58983457]
 [ 0.48793543]
 [ 1.13202159]]


In [60]:
XT = np.transpose(X)

In [61]:
beta = np.linalg.inv(XT.dot(X)).dot(XT).dot(Y)

In [62]:
beta

array([[-0.39778687],
       [ 0.12135876],
       [ 0.40011832],
       [ 0.71056352],
       [ 0.53598602],
       [ 0.27741394],
       [ 0.46661166],
       [ 0.33514024],
       [-0.37397644],
       [-0.68414123]])

In [63]:
Y_cap = X.dot(beta)

In [64]:
h = Y_cap - Y

In [65]:
h.T.dot(Y_cap)

array([[  9.82025309e-16]])

In [67]:
Y_cap - Y

array([[  9.21485110e-15],
       [ -9.43689571e-16],
       [ -1.11022302e-15],
       [  7.77156117e-16],
       [  2.83106871e-15],
       [  7.77156117e-16],
       [ -1.55431223e-15],
       [  3.55271368e-15],
       [  1.60982339e-15],
       [ -3.99680289e-15]])

In [ ]:
np.